name: DotNet Development

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - uses: microsoft/setup-msbuild@main
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@main
        with:
          nuget-version: "latest"

      - name: NuGet restore
        run: nuget restore src/Wpf.Ui.Demo.sln

      - name: Build
        run: msbuild src/Wpf.Ui.sln -p:Configuration=Release -m

      - name: Publish net90
        uses: actions/upload-artifact@main
        id: publish_net9
        with:
          name: WPFUI_DEMO-NET9
          path: |
            src/Wpf.Ui.Demo/bin/Release/net9.0-windows10.0.22000.0
